name: acr_cloud_sdk_example
description: Demonstrates how to use the acr_cloud_sdk plugin.
version: 0.0.1
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  acr_cloud_sdk:
    path: ../
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-beta7
  hooks_riverpod: ^0.13.1
  flutter_hooks: ^0.16.0
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  modal_bottom_sheet: ^2.0.00
  google_fonts: ^2.0.0
  flutter_spinkit: ^5.0.0

  shared_preferences: ^2.0.5
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/