name: lyrics
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  http: any
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  fonts:
  - family: PlayfairDisplay
    fonts:
      - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
      - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
        style: italic